version: '3.8'

services:
  app:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0

  # Add a database service if needed
  # db:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: visitor_db
  #     POSTGRES_USER: visitor_user
  #     POSTGRES_PASSWORD: visitor_password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: 